#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# M. Martin 05.12.2019
# Creates a service for each ipsec phase 1
# and groups its phase 2 in it.

def inventory_fortigate_ipsec_ph1(info):
    for ph1 in info:
        yield ph1[0], None


def check_fortigate_ipsec_ph1(item, params, info):
    p1s = {}
    for p1, p2, status in info:
        if p1 == item:
            if p1 not in p1s:
                p1s[p1] = []
            if len(p1s[p1]) == 0:
                p1s[p1].append({'p2name' : p2,
                                'status' : status})
            else:
                present = False
                for ph2 in p1s[p1]:
                    if ph2['p2name'] == p2:
                        present = True
                        break
                if not present:
                    p1s[p1].append({'p2name' : p2,
                                    'status' : status})
                                   
    tunnels_down    = []
    for i in p1s[item]:
        if i['status'] == "1":
            tunnels_down.append(i['p2name'])

    num_total        = len(p1s[item])
    num_down         = len(tunnels_down)
    num_up           = num_total - num_down

    infotext = "Total: %d, Up: %d, Down: %d" % \
               (num_total, num_up, num_down)

    warn, crit = 1, num_total
    status = 0
    if crit is not None and num_down >= crit:
        status = 2
    elif warn is not None and num_down >= warn:
        status = 1
    if status:
        infotext += " (warn/crit at %s/%s)" % (warn, crit)
    if tunnels_down:
        infotext += ", Tunnels: %s" % (", ".join(tunnels_down))

    return status, infotext, [('active_vpn_tunnels', num_up, '', '', 0, num_total)]


check_info["fortigate_ipsec_ph1"] = {
    "inventory_function"        : inventory_fortigate_ipsec_ph1,
    "check_function"            : check_fortigate_ipsec_ph1,
    "service_description"       : "VPN IPSec Tunnel %s",
    "has_perfdata"              : True,
    "snmp_scan_function"        : lambda oid: ".1.3.6.1.4.1.12356.101.1" in oid(".1.3.6.1.2.1.1.2.0"),
    "snmp_info"                 : (".1.3.6.1.4.1.12356.101.12.2.2.1", [
                                    2,  # fgVpnTunEntPhase1Name
                                    3,  # fgVpnTunEntPhase2Name
                                    20, # fgVpnTunEntStatus
                                  ]),
    #"group"                     : "ipsecvpn",
}

