#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
#################################################################
# Description: Checks the status of the FortiADC RealServers    #
#################################################################

# .1.3.6.1.4.1.12356.112.3.2.1.1.1 = INTEGER: 1
# .1.3.6.1.4.1.12356.112.3.2.1.1.2 = INTEGER: 2
# .1.3.6.1.4.1.12356.112.3.2.1.2.1 = STRING: "test"
# .1.3.6.1.4.1.12356.112.3.2.1.2.2 = STRING: "vs-test"
# .1.3.6.1.4.1.12356.112.3.2.1.3.1 = STRING: "Enable"
# .1.3.6.1.4.1.12356.112.3.2.1.3.2 = STRING: "Enable"
# .1.3.6.1.4.1.12356.112.3.2.1.4.1 = STRING: "HEALTHY"
# .1.3.6.1.4.1.12356.112.3.2.1.4.2 = STRING: "HEALTHY"
# .1.3.6.1.4.1.12356.112.3.2.1.5.1 = INTEGER: 0
# .1.3.6.1.4.1.12356.112.3.2.1.5.2 = INTEGER: 0
# .1.3.6.1.4.1.12356.112.3.2.1.6.1 = INTEGER: 0
# .1.3.6.1.4.1.12356.112.3.2.1.6.2 = INTEGER: 0
# .1.3.6.1.4.1.12356.112.3.2.1.7.1 = INTEGER: 0
# .1.3.6.1.4.1.12356.112.3.2.1.7.2 = INTEGER: 0
# .1.3.6.1.4.1.12356.112.3.2.1.8.1 = STRING: "root"
# .1.3.6.1.4.1.12356.112.3.2.1.8.2 = STRING: "root"

def inventory_fortiadc_virtsrv(info):
    for name, status, health in info:
        #if status == "Enable":
            yield name, None

def check_fortinet_virtsrv(item, _no_params, info):
    for name, status, health in info:
        if name == item:
            if health == "HEALTHY":
                return 0, "VirtualServer is " + health
            elif health == "DISABLE" or health == "MAINTAINED" or health == "UNHEALTHY":
                return 1, "VirtualServer is " + health
            elif health == "DEAD":
                return 2, "VirtualServer is " + health + "!"
            else:
                return 3, "state not implemented."

check_info["fortiadc_virtsrv"] = {
    "inventory_function"    : inventory_fortiadc_virtsrv,
    "check_function"        : check_fortinet_virtsrv,
    "service_description"   : "VirtualServer %s",
    "has_perfdata"          : False,
    # uses mib FORTINET-MIB-280
    "snmp_scan_function"    : lambda oid: ".1.3.6.1.4.1.12356.112.100.30" in oid(".1.3.6.1.2.1.1.2.0"),
    "snmp_info"             : ( ".1.3.6.1.4.1.12356.112.3.2.1", [
                                    "2", # VSName
                                    "3", # VSStatus
                                    "4", # VSHealth
                              ])
}